# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Learning' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Learning
  pod 'SDWebImage', '~> 5.1.0'

  target 'LearningTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LearningUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end
